services:
  - type: web
    name: venom-kazino
    runtime: node
    plan: free
    rootDir: venom-kazino
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_VERSION
        value: 20
